services:
  - type: web
    name: baraka-bundle-ai-tools
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: REACT_APP_OPENAI_API_KEY
        sync: false
    # Force rebuild to include enhanced TTS components
    # Build updated: 2025-09-17 with enhanced Islamic TTS