services:
  - type: web
    name: baraka-bundle-ai-tools
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: REACT_APP_OPENAI_API_KEY
        sync: false
      - key: VITE_OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
    # Force rebuild to include enhanced TTS components
    # Build updated: 2025-09-17 with OpenAI TTS integration